#include "rs485_bringup.h"

#include "usart.h"
#include <stddef.h>

/* UART4 in RS-485 mode is generated by CubeMX */
extern UART_HandleTypeDef huart4;

HAL_StatusTypeDef RS485_Init(void)
{
    /* If CubeMX has already called MX_UART4_Init(), huart4 should be ready.
       We keep this function as a single entry point for future extensions:
       - set up DMA
       - add a TX mutex
       - add async RX
    */
    if (huart4.Instance == NULL)
        return HAL_ERROR;

    return HAL_OK;
}

HAL_StatusTypeDef RS485_Tx(const uint8_t *data, uint16_t len, uint32_t timeout_ms)
{
    if (data == NULL || len == 0U)
        return HAL_ERROR;

    return HAL_UART_Transmit(&huart4, (uint8_t*)data, len, timeout_ms);
}

HAL_StatusTypeDef RS485_Rx(uint8_t *data, uint16_t len, uint32_t timeout_ms)
{
    if (data == NULL || len == 0U)
        return HAL_ERROR;

    return HAL_UART_Receive(&huart4, data, len, timeout_ms);
}
